// <auto-generated />
namespace FinalYearProjectClassified.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addpropertiestouserclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpropertiestouserclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201602181651303_add properties to user class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
